import type { ConfigKey } from "../types";

export const CodeSnapConfigNames = [
  "backgroundColor",
  "boxShadow",
  "containerPadding",
  "realLineNumbers",
  "roundedCorners",
  "showLineNumbers",
  "showWindowControls",
  "showWindowTitle",
  "shutterAction",
  "target",
  "transparentBackground",
] as const;

export const extensionSettingsNames: ConfigKey[] = [
  ...CodeSnapConfigNames,
  "backgroundColor",
  "boxShadow",
  "containerPadding",
  "defaultWatermarkText",
  "enableResizing",
  "enableSymbolBreadcrumb",
  "fullLinesSelection",
  "highlightLineNumber",
  "linkOnOpen",
  "lockOnOpen",
  "maxCharWidth",
  "optimizeSvg",
  "realLineNumbers",
  "roundedCorners",
  "roundingLevel",
  "saveFormat",
  "saveScale",
  "showLineNumbers",
  "showWindowControls",
  "showWindowTitle",
  "shutterAction",
  "target",
  "transparentBackground",
  "uiCustomColors",
  "useFallbackPngExporter",
  "watermark",
  "watermarkPosition",
  "windowIconType",
  "windowStyle",
  "windowTitleTemplate",
] as const;
