name: Generate Badges

on:
  schedule:
    - cron: "0 */12 * * *" 
  
  workflow_dispatch:

  push:
    branches:
    - main
  
jobs:
    generate-badges:
      permissions: 
        contents: write
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: "22.x"

        - name: Install Dependencies
          run: yarn install --frozen-lockfile

        - name: Generate Badges
          run: node ./scripts/make-badges.js
          
        - name: Push Badges to badges branch
          uses: crazy-max/ghaction-github-pages@v3.1.0
          with:
            target_branch: Badges
            build_dir: badges
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
